// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAWeyu4WYAvDaMtlbs72jyklAv6yQNPQw',
    appId: '1:777878391684:web:1d00c546b4d700f2cc6bd1',
    messagingSenderId: '777878391684',
    projectId: 'test-project-5e57a',
    authDomain: 'test-project-5e57a.firebaseapp.com',
    storageBucket: 'test-project-5e57a.firebasestorage.app',
    measurementId: 'G-NVZJQT0F8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaF6UseKOmc-Om_4Seb-b8IOC9ZQl-EBw',
    appId: '1:777878391684:android:256be834319893e4cc6bd1',
    messagingSenderId: '777878391684',
    projectId: 'test-project-5e57a',
    storageBucket: 'test-project-5e57a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEftPEytSYRHxX4AXsSxnN4rk0M_5YETs',
    appId: '1:777878391684:ios:31824c6d0a217fb3cc6bd1',
    messagingSenderId: '777878391684',
    projectId: 'test-project-5e57a',
    storageBucket: 'test-project-5e57a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEftPEytSYRHxX4AXsSxnN4rk0M_5YETs',
    appId: '1:777878391684:ios:31824c6d0a217fb3cc6bd1',
    messagingSenderId: '777878391684',
    projectId: 'test-project-5e57a',
    storageBucket: 'test-project-5e57a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAWeyu4WYAvDaMtlbs72jyklAv6yQNPQw',
    appId: '1:777878391684:web:3a5edcf624f89704cc6bd1',
    messagingSenderId: '777878391684',
    projectId: 'test-project-5e57a',
    authDomain: 'test-project-5e57a.firebaseapp.com',
    storageBucket: 'test-project-5e57a.firebasestorage.app',
    measurementId: 'G-LG42BPQ8WV',
  );
}
