// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaqSHcLppd8eOjRajrQH9U61LXZg9WceI',
    appId: '1:986648440063:web:c5998afccc5295244930ca',
    messagingSenderId: '986648440063',
    projectId: 'final-exam-b496d',
    authDomain: 'final-exam-b496d.firebaseapp.com',
    storageBucket: 'final-exam-b496d.firebasestorage.app',
    measurementId: 'G-MP0BDLK7J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6I2SVfM3TWkSuINZNcdK03KnV00PXJt8',
    appId: '1:986648440063:android:a9bed08bb3c8195d4930ca',
    messagingSenderId: '986648440063',
    projectId: 'final-exam-b496d',
    storageBucket: 'final-exam-b496d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu36tpGTPUyeYpzGuH8IUYYYw0hfS_Voo',
    appId: '1:986648440063:ios:fbcdefef4f81b6154930ca',
    messagingSenderId: '986648440063',
    projectId: 'final-exam-b496d',
    storageBucket: 'final-exam-b496d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalExamPuc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu36tpGTPUyeYpzGuH8IUYYYw0hfS_Voo',
    appId: '1:986648440063:ios:fbcdefef4f81b6154930ca',
    messagingSenderId: '986648440063',
    projectId: 'final-exam-b496d',
    storageBucket: 'final-exam-b496d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalExamPuc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaqSHcLppd8eOjRajrQH9U61LXZg9WceI',
    appId: '1:986648440063:web:86399a4bed1a956e4930ca',
    messagingSenderId: '986648440063',
    projectId: 'final-exam-b496d',
    authDomain: 'final-exam-b496d.firebaseapp.com',
    storageBucket: 'final-exam-b496d.firebasestorage.app',
    measurementId: 'G-DW06MVTTM4',
  );
}
