// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXXGRVtO2Y5SlSIw8ifB_-bcZfIWcmjjQ',
    appId: '1:1088844923210:web:952c22c194a196b7dfc1b3',
    messagingSenderId: '1088844923210',
    projectId: 'authproject-e65a4',
    authDomain: 'authproject-e65a4.firebaseapp.com',
    storageBucket: 'authproject-e65a4.firebasestorage.app',
    measurementId: 'G-W37D35LRK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiHlaF-1b_X4xdiyCt_TszPIX4r2EGhr8',
    appId: '1:1088844923210:android:4b350b2c51d66fc8dfc1b3',
    messagingSenderId: '1088844923210',
    projectId: 'authproject-e65a4',
    storageBucket: 'authproject-e65a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdsLQZ1UWY9rysvgTy449_io2LR3aXWUk',
    appId: '1:1088844923210:ios:77752761cef8e8b4dfc1b3',
    messagingSenderId: '1088844923210',
    projectId: 'authproject-e65a4',
    storageBucket: 'authproject-e65a4.firebasestorage.app',
    iosBundleId: 'com.example.crudApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdsLQZ1UWY9rysvgTy449_io2LR3aXWUk',
    appId: '1:1088844923210:ios:77752761cef8e8b4dfc1b3',
    messagingSenderId: '1088844923210',
    projectId: 'authproject-e65a4',
    storageBucket: 'authproject-e65a4.firebasestorage.app',
    iosBundleId: 'com.example.crudApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXXGRVtO2Y5SlSIw8ifB_-bcZfIWcmjjQ',
    appId: '1:1088844923210:web:3aeffe7e67380fd2dfc1b3',
    messagingSenderId: '1088844923210',
    projectId: 'authproject-e65a4',
    authDomain: 'authproject-e65a4.firebaseapp.com',
    storageBucket: 'authproject-e65a4.firebasestorage.app',
    measurementId: 'G-XS4QG8B290',
  );
}
