// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXb-Ams7oQmGjKf67YUu911Et0OFT2byU',
    appId: '1:469959662594:web:85c21709bc28b3b4e75b1b',
    messagingSenderId: '469959662594',
    projectId: 'our-new-application',
    authDomain: 'our-new-application.firebaseapp.com',
    storageBucket: 'our-new-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNFKrv4A9ZFeNCqelh4N6SoZR85dbDPYQ',
    appId: '1:469959662594:android:aa8a37f0c285fbcae75b1b',
    messagingSenderId: '469959662594',
    projectId: 'our-new-application',
    storageBucket: 'our-new-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsYYN36FMRtmxCajCGQY01njvDk9x8PVc',
    appId: '1:469959662594:ios:77a9e4a57dd56192e75b1b',
    messagingSenderId: '469959662594',
    projectId: 'our-new-application',
    storageBucket: 'our-new-application.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsYYN36FMRtmxCajCGQY01njvDk9x8PVc',
    appId: '1:469959662594:ios:77a9e4a57dd56192e75b1b',
    messagingSenderId: '469959662594',
    projectId: 'our-new-application',
    storageBucket: 'our-new-application.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXb-Ams7oQmGjKf67YUu911Et0OFT2byU',
    appId: '1:469959662594:web:3b122ecd714b99fae75b1b',
    messagingSenderId: '469959662594',
    projectId: 'our-new-application',
    authDomain: 'our-new-application.firebaseapp.com',
    storageBucket: 'our-new-application.firebasestorage.app',
  );
}
